version: '3.8'

services:
  client:
    build: ./client/vite-project
    ports:
      - "5173:5173"
    
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env